include: package:flutter_lints/flutter.yaml

analyzer:
# enable-experiment:
#   - macros
  errors:
    invalid_override_of_non_virtual_member: error

linter:
  rules:
    prefer_const_constructors: true
